---
latitude: 27.10449
longitude: -82.43455
map_zoom: 12
name: Ramada Venice Hotel Venezia
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 425 Us Highway 41 Byp N
  street2: ''
  state: Florida
  city: Venice
  country: United States
  zip_code: '34285'
_hotel_id: RAM728
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt
